- name: Ensure {{ journal_log_path }} exists
  become: yes
  file:
    path: "{{ journal_log_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775

- name: Store journal logs in {{ journal_log_file_name }}
  become: yes
  shell:
    cmd: |
      /bin/journalctl -a > {{ journal_log_file_name }}

- name: Set journal.log file permissions
  become: yes
  file:
    path: '{{ journal_log_file_name }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0644
